/** @format */

export default {
  SET_REGION: "SET_REGION",
  SET_DEFAULTS: "SET_DEFAULTS",
  SET_OS: "SET_OS",
  SET_SELECTED_REGION: "SET_SELECTED_REGION",
  SET_SELECTED_OS: "SET_SELECTED_OS",
  SET_INSTANCE_DATA: "SET_INSTANCE_DATA",
  SET_RECOMMENDATION_DETAILS: "SET_RECOMMENDATION_DETAILS",
  SET_DEFAULT_PRICING: "SET_DEFAULT_PRICING",
  SET_RESERVED_INSTANCE_DATA: "SET_RESERVED_INSTANCE_DATA",
  SET_PRICING_DISPLAY_DATA: "SET_PRICING_DISPLAY_DATA",
  SET_ESTIMATES: "SET_ESTIMATES",
};
